### PR TITLE
Add sentimentHQ support for php

### PR DESCRIPTION
**Pull request by anneCarlson**

### CODE REVIEW

**Comment by sihrc** [comment]
@anneCarlson I think because sentimenthq is only in private beta, we want to 1) comment out the sentimenthq tests for now, and 2) only allow users to use sentimentHq if they're on a private cloud or otherwise raise an exception saying it's only in private beta.

**Comment by anneCarlson** [comment]
Ahh, didn't know it was only in private beta. Commenting out the tests sounds good, but I feel like if we want to raise an informative error message, that should be on serverside.

**Comment by sihrc** [comment]
It probably makes more sense to be on the server, but this is only a temporary thing. Theoretically it will be public later. So the REST Api would totally work. Right now, we have it handled on the client side in ruby and python.

**Comment by anneCarlson** [comment]
So, putting only temporary stuff on the client side seems like a poor idea. That means users who download the module while that is in beta will have to re-download it and change their version number if they want to use sentimentHQ when it comes out. It also means we need to update every client library when we push that update.

**Comment by anneCarlson** [comment]
@sihrc @madisonmay @jagreene Can I get a final glance from one of you before merging, since this is kind of old?

**Comment by madisonmay** [comment]
Looks good, rebase and merge?

**Comment by madisonmay** [comment]
Ready to go once tests pass...

**Pull request merged**
